blog_main/blog_posts/forms.py
# under blog_posts/forms.py 

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired()])
    text = TextAreaField('Text',validators=[DataRequired()])
    submit = SubmitField("Post")

blog_main/blog_posts/views.py
# under blog_posts/views.py

from turtle import title
from flask import Flask,render_template,request,redirect,Blueprint,url_for,flash
from flask_login import current_user,login_required
from flask_migrate import current
from blog_main import db
from blog_main.model import BlogPost
from blog_main.blog_posts.forms import BlogPostForm
from flask import abort

blog_posts = Blueprint('blog_posts',__name__)

## Views 
# Create
# Blogposts (view)
# Update
# Delete


# Create

@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()
    
    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data,
            text=form.text.data,
            user_id=current_user.id)

        db.session.add(blog_post)
        db.session.commit()
        flash('Blog Post Created')
        return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)


# Blogposts (view)

@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title, date=blog_post.date, post=blog_post)



# Update

@blog_posts.route('/<int:blog_post_id>/update',methods=['GET','POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post.title=form.title.data
        blog_post.text=form.text.data

        db.session.commit()
        flash('Blog Post Updated')
        return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post_id))

    elif request.method=='GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template('create_post.html',title='Updating',form=form)

# Delete

@blog_posts.route('/<int:blog_post_id>/update',methods=['GET','POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash("blog post deleted")

    return redirect(url_for('core.index'))

blog_main/core/views.py
## Under cores/views.py 

from flask import render_template,request,Blueprint

from blog_main.model import BlogPost

core = Blueprint('core',__name__)

@core.route('/')
def index():
    #more to come!
    ## now

    page = request.args.get('page',1,type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('index.html',blog_posts=blog_posts)

@core.route('/info')
def info():

    return render_template('info.html')
    

blog_main/users/views.py
## under users/views.py

# register
# login 
# logout
# account(update flaskform)
# user's list of BlogPosts


from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user,current_user,logout_user,login_required
from blog_main import db
from blog_main.model import User,BlogPost
from blog_main.users.forms import RegistrationForm,LoginForm,UpdateUserForm
from blog_main.users.picture_handler import add_profile_pic


users = Blueprint('users',__name__)

# register

@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)   ### creating a user and adding them in

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering!')
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)


# login 

@users.route('/login',methods=['GET','POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash("login successful!")

            next = request.args.get('next')
            if next==None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form= form)

# logout

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for("core.index"))


# account(update flaskform)

@users.route('/account',methods=['GET','POST'])
@login_required
def account():

    form = UpdateUserForm()
    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username) ## imported from picture_handler.py
            current_user.profile_image = pic ## gives a path to image.

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("User Account Updated!")
        return redirect(url_for('users.account'))

    elif request.method =='GET':
        form.username.data=current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static',filename = 'profile/pics/'+current_user.profile_image)
    return render_template('account.html',profile_image=profile_image,form=form)

# user's list of BlogPosts

@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('user_blog_posts.html',blog_posts=blog_posts,user=user)

    ############### end #######

blog_main/templates/account.html
{% extends "base.html" %}
{% block content %}

    <div class="jumbotron">
        <div align="center">
            <h1>Welcome to the page {{current_user.username}}</h1>
            <img align="center" src="{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}">
        </div>
    </div>

    <div class="container">
        <form method="POST" action="" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            <div class="form-group">
                {{form.username.label(class='form-group')}}{{form.username(class='form-control')}} <br>
            </div>
            <div class="form-group">
                {{form.email.label(class='form-group')}}{{form.email(class='form-control')}} <br>
            </div>
            <div class="form-group">
                {{form.picture.label(class='form-group')}}{{form.picture(class='form-control')}} <br>
            </div>
            <div class="form-group">
                {{form.submit(class='btn btn-primary')}}
            </div>
        </form>
    </div>

{% endblock %}

blog_main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Bootstrap cdn -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <!-- Navigation bar -->

    <ul class="nav">
        <li class="nav-link">
            <a href="{{url_for('core.index')}}">Home</a>
        </li>
        <li class="nav-link">
            <a href="{{url_for('core.info')}}">About</a>
        </li>

        {% if current_user.is_authenticated %}


            <li class="nav-link">
                <a href="{{url_for('users.logout')}}">Log out</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('users.account')}}">Account</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('blog_posts.create_post')}}">create post</a>
            </li>

        {% else %}

            <li class="nav-link">
                <a href="{{url_for('users.login')}}">Log in</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('users.register')}}">register</a>
            </li>
        
        {% endif %}

    </ul>
    
    <!-- end of Navigation -->

    <!-- main body -->

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

    <!-- end of main body -->
</body>
</html>

blog_main/templates/blog_post.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
    <h1>{{post.title}}</h1>
    <h2>Written by : {{post.author.username}}</h2>
    <h3>Published : {{post.date.strftime('%B %d, %Y')}}</h3>

    <p>{{post.text}}</p>

    {% if post.author == current_user %}
        <div>
            <a href="{{url_for('blog_posts.update',blog_post_id = post.id)}}">Update</a>
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal ">Delete</button>
        </div>

    {% endif %}
</div>

<div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete post</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure , you want to delete the post?</p>
        </div>
        <div class="modal-footer">
          <form action="{{url_for('blog_posts.delete_post',blog_post_id=post.id)}}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
          
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

blog_main/templates/create_post.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <form action="" class="form-group" method="POST">
        {{form.hidden_tag()}}

        <div class="form-group">
            {{form.title.label(class='form-control-label')}}
            {{form.title(class='form-control form-control-lg')}}
        </div>

        <div class="form-group">
            {{form.text.label(class='form-control-label')}}
            {{form.text(class='form-control form-control-lg')}}
        </div>

        <div class="form-group">
            {{form.submit(class='btn btn-outline-info')}}
        </div>
    </form>
</div>

{% endblock %}

blog_main/templates/index.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
    <h1>mechmaster blogs</h1>
</div>

<div class="container">
    {% for post in blog_posts.items %}

    <div class="card">
        <div class="card-body">
            <h2><a class='card-title' href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2>
            <a href="{{url_for('users.user_posts',username=post.author.username)}}">Written by : {{post.author.username}}</a>
            <p>Published on : {{post.date.strftime('%Y-%m-%d')}}</p>
            <a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}" class="btn btn-primary">Read Blog Post</a>
        </div>
    </div>

    {% endfor %}
</div>

<!-- -----This is bootstrap pagination---------- -->
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
            {% if blog_posts.page == page_num %}

            <li class="page-item-disabled">
                <a href="{{url_for('core.index',page=page_num)}}" class="page-link">{{page_num}}</a>
            </li>

            {% else %}

            <li class="page-item">
                <a href="{{url_for('core.index',page=page_num)}}" class="page-link">{{page_num}}</a>
            </li>

            {% endif %}

        {% endfor %}
    </ul>
  </nav>

{% endblock %}

blog_main/templates/info.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
    <h1>Info of our company</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut, numquam!
       Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus unde esse a nihil voluptates hic delectus culpa corporis consectetur minus.
    </p>
</div>

{% endblock %}

blog_main/templates/login.html
{% extends "base.html" %}
{% block content %}

    <form method="POST">
        {{form.hidden_tag()}}
        {{form.email.label}}{{form.email}} <br>
        {{form.password.label}}{{form.password}} <br>
        {{form.submit()}}
    </form>

{% endblock %}

blog_main/templates/register.html
{% extends "base.html" %}
{% block content %}

    <form method="POST">
        {{form.hidden_tag()}}
        {{form.email.label}}{{form.email}} <br>
        {{form.username.label}}{{form.username}} <br>
        {{form.password.label}}{{form.password}} <br>
        {{form.pass_confirm.label}}{{form.pass_confirm}} <br>
        {{form.submit()}}
    </form>

{% endblock %}

blog_main/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <div class="jumbotron">
        <div align="center">
            <h1> Welcome to the page for {{user.username}}</h1>
            <img src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}" alt="">

        </div>
    </div>


    {% for post in blog_posts.items %}
    <h2><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2>
    Written By : <a href="{{url_for('users.user_posts',username=post.author.username)}}">{{post.author.username}}</a>
    <p class="text-muted">Published on : {{post.date.strftime('%Y-%m-%d')}}</p>
    <br>
    <p>{{post.text}}</p>
    <br>

    {% endfor %}

    <!-- -----This is bootstrap pagination---------- -->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
                {% if blog_posts.page == page_num %}

                <li class="page-item-disabled">
                    <a href="{{url_for('users.user_posts',username=user.username,page=page_num)}}" class="page-link">{{page_num}}</a>
                </li>

                {% else %}

                <li class="page-item">
                    <a href="{{url_for('users.user_posts',username=user.username,page=page_num)}}" class="page-link">{{page_num}}</a>
                </li>

                {% endif %}

            {% endfor %}
        </ul>
      </nav>

</div>

{% endblock %}